import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav style={{ padding: 16, borderBottom: "1px solid #ddd" }}>
          <a href="/" style={{ marginRight: 12 }}>Home</a>
          <a href="/auth" style={{ marginRight: 12 }}>Login</a>
          <a href="/new-item" style={{ marginRight: 12 }}>New item</a>
          <a href="/my-items" style={{ marginRight: 12 }}>My items</a>
          <a href="/booking-requests" style={{ marginRight: 12 }}>Booking requests</a>
          <a href="/my-bookings" style={{ marginRight: 12 }}>My bookings</a>
        </nav>

        <div style={{ padding: 16 }}>{children}</div>
      </body>
    </html>
  );
}