export const neighborhoodsByCity: Record<string, string[]> = {
  Zagreb: [
    "Blato",
    "Borongaj",
    "Borovje",
    "Botinec",
    "Brestje",
    "Brezovica",
    "Bukovac",
    "Buzin",
    "Centar",
    "Črnomerec",
    "Čulinec",
    "Cvjetno naselje",
    "Dubec",
    "Dubrava",
    "Dugave",
    "Ferenščica",
    "Folnegovićevo",
    "Gajnice",
    "Gračani",
    "Ivanja Reka",
    "Jakuševec",
    "Jankomir",
    "Jarun",
    "Kajzerica",
    "Kanal",
    "Klara",
    "Knežija",
    "Kruge",
    "Ksaver",
    "Kustošija",
    "Kvatrić",
    "Lanište",
    "Lučko",
    "Ljubljanica",
    "Maksimir",
    "Malešnica",
    "Markuševec",
    "Medveščak",
    "Mikulići",
    "Mlinovi",
    "Peščenica",
    "Podsused",
    "Poljanice",
    "Prečko",
    "Ravnice",
    "Remete",
    "Remetinec",
    "Retkovec",
    "Rudeš",
    "Savica",
    "Savski gaj",
    "Šestine",
    "Sesvete",
    "Sigečica",
    "Siget",
    "Sloboština",
    "Sopot",
    "Špansko",
    "Središće",
    "Srednjaci",
    "Stenjevec",
    "Stupnik",
    "Sveta Nedelja",
    "Svetice",
    "Travno",
    "Trešnjevka",
    "Trnava",
    "Trnovčica",
    "Trnsko",
    "Trnje",
    "Trokut",
    "Utrina",
    "Veliko Polje",
    "Volovčica",
    "Voltino",
    "Vrapče",
    "Vrbani",
    "Vrbik",
    "Vukomerec",
    "Zapruđe",
    "Zavrtnica",
    "Žitnjak",
  ],
  Split: [
    "Bačvice",
    "Bilice",
    "Blatine",
    "Bol",
    "Brda",
    "Dobri",
    "Dračevac",
    "Dragovode",
    "Duilovo",
    "Dujmovača",
    "Firule",
    "Glavičine",
    "Grad",
    "Gripe",
    "Kacunar",
    "Kila",
    "Kman",
    "Kopilica",
    "Križine",
    "Lokve",
    "Lora",
    "Lovret",
    "Lovrinac",
    "Lučac",
    "Manuš",
    "Mejaši",
    "Meje",
    "Mertojak",
    "Neslanovac",
    "Pazdigrad",
    "Plokite",
    "Poljud",
    "Pujanke",
    "Radunica",
    "Ravne njive",
    "Sirobuja",
    "Skalice",
    "Škrape",
    "Smokovik",
    "Smrdečac",
    "Spinut",
    "Stinice",
    "Sućidar",
    "Sukojišan",
    "Sustipan",
    "Table",
    "Trstenik",
    "Veli Varoš",
    "Visoka",
    "Vranjic",
    "Žnjan",
    "Zvončac",
  ],
  Rijeka: [
    "Banderovo",
    "Belveder",
    "Bivio",
    "Brajda",
    "Brašćine",
    "Bulevard",
    "Centar",
    "Donja Drenova",
    "Gornja Drenova",
    "Gornja Vežica",
    "Grbci",
    "Grobnik",
    "Kantrida",
    "Kastav",
    "Kostrena",
    "Kozala",
    "Krimeja",
    "Krnjevo",
    "Martinkovac",
    "Matulji",
    "Mlaka",
    "Orehovica",
    "Pašac",
    "Pećine",
    "Pehlin",
    "Podmurvice",
    "Podvežica",
    "Potok",
    "Pulac",
    "Rastočine",
    "Rujevica",
    "Školjić",
    "Škurinje",
    "Škurinjska Draga",
    "Srdoči",
    "Sušačka Draga",
    "Sušak",
    "Sv. Kuzam",
    "Trsat",
    "Turnić",
    "Viškovo",
    "Vojak",
    "Zamet",
  ],
  Zadar: [
    "Arbanasi",
    "Belafuža",
    "Bili Brig",
    "Brodarica",
    "Crvene Kuće",
    "Diklo",
    "Donji Brig",
    "Dražanica",
    "Dražnice",
    "Gaj",
    "Gaženica",
    "Gornji Bilig",
    "Jazine 1",
    "Jazine 2",
    "Kolovare",
    "Martinovo",
    "Maslina",
    "Mocire",
    "Novi Bokanjac",
    "Petrić",
    "Plovanija",
    "Poluotok",
    "Puntamika",
    "Ravnice",
    "Ričina",
    "Sinjoretovo",
    "Skročini",
    "Smiljevac",
    "Špada",
    "Stanovi",
    "Stari Bokanjac",
    "Višnjik",
    "Voštarnica",
  ],
  Osijek: [
    "Borova",
    "Centar",
    "Dionica",
    "Donji Grad",
    "Gornji Grad",
    "Industrijska četvrt",
    "Jug I",
    "Jug II",
    "Našičko naselje",
    "Pampas",
    "Pustara",
    "Retfala",
    "Sjenjak",
    "Stadionsko naselje",
    "Tvrđa",
    "Zapadno predgrađe",
    "Zeleno polje",
  ],
  "Velika Gorica": [
    "Čiče",
    "Mraclin",
    "Šćitarjevo",
    "Velika Gorica",
    "Velika Kosnica",
    "Velika Mlaka",
    "Vukomerić",
  ],
  "Varaždin": [
    "Ivanec",
    "Ludbreg",
    "Novi Marof",
    "Varaždin",
    "Varaždinske toplice",
  ],
};
